#!/bin/bash
#colors 
RED="$(printf '\033[31m')"  
GREEN="$(printf '\033[32m')"  
ORANGE="$(printf '\033[33m')"  
BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  
CYAN="$(printf '\033[36m')"  
WHITE="$(printf '\033[37m')" 
BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  
GREENBG="$(printf '\033[42m')"  
ORANGEBG="$(printf '\033[43m')"  
BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  
CYANBG="$(printf '\033[46m')" 
WHITEBG="$(printf '\033[47m')"
BLACKBG="$(printf '\033[40m')"
RESETBG="$(printf '\e[0m')"
BLINK="$(printf '\033[5;31m')"
echo ""
echo $BLUE"[1] Debian OS"$RESETBG
echo $BLUE"[2] Termux"$RESETBG
read -p $GREEN"Choose According to you: "$RESETBG Choose
if [ $Choose -eq 1 ]; then
  sudo install python python2 python3
  sudo apt python3-pip
  echo $BLUE"Installation Successfull"$RESETBG
  sleep 2
  clear
  ./meme
fi

if [ $Choose -eq 2 ]; then
  apt update && apt upgrade -y
  apt install python python2 python3
  apt install python3-pip
  echo $BLUE"Installation Successfull"$RESETBG
  sleep 2
  clear
  ./meme
fi
